apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubaction-aks-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: githubaction-aks-demo-app
  template:
    metadata:
      labels:
        app: githubaction-aks-demo-app
    spec:
      containers:
      - name: my-app-container
        image: lavinacr.azurecr.io/mygradezimage:${{github.sha}}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: lavinacr-registry-connection
    
    
