apiVersion: v1
kind: Service
metadata:
  name: githubaction-aks-demo-service
spec:
  selector:
    app: githubaction-aks-demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer